### ISSUE TITLE
Feature request: css code transpiling

### ISSUE THREAD

**Issue by serhiijun** [camertron/rux#8]
Same to css-in-js it would be fine to have bundled css from my rux component too.
Let's say, we have this folder structure:
```
my_component
--my_component.rux
--my_component.css
--my_component.rcss
```
And my_component.rux looks like this
```ruby
class Ui::Mix::Home::SpacecraftItemComponent::SpacecraftItemComponent < ViewComponent::Base
  include Birdel::Component

  Styles = Data.define(
    :wrapper,
    :avatar,
    :name
  )
  attr_reader :spacecraft
  def initialize(spacecraft:)
    @spacecraft = spacecraft
  end

  def styles
    @styles ||= Styles.new(
      wrapper: "wrapper",
      avatar: "avatar",
      name: "name"
    )
  end

  def call
    <div class={css_class} data-controller={css_class}>
      <div class={styles.wrapper} data-action={events.handleClickItem}>
        <div class={styles.avatar}>
        </div>
        <div class={styles.name}>
          {spacecraft.name}
        </div>
      </div>
    </div>
  end
end
```

And `my_component.rcss` like this:
```css
.wrapper{
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  padding: 10px;
}
.avatar{
  width: 32px;
  height: 32px;
  border-radius: 15px;
  background-color: #001eff;
  background-size: 75%;
  background-position: center;
  background-repeat: no-repeat;
  background-image: var(--some-avatar-url)
}
.name{
  font-size: 14px;
}
```

And while Rux transpiles .rux component - it also transpiles .rcss file from this component to .css file, which may looks like this after:

```css
.wrapper_pvsbv6dH6Fdf4{
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  padding: 10px;
}
.avatar_87dGHbdfhb{
  width: 32px;
  height: 32px;
  border-radius: 15px;
  background-color: #001eff;
  background-size: 75%;
  background-position: center;
  background-repeat: no-repeat;
  background-image: var(--some-avatar-url)
}
.name_hgv6Hbdf{
  font-size: 14px;
}
```

As you can see - now our css selectors is uniq.
Why we need that - well, this is super simple example, but let's imagine we have 50 components. Each of them may have .wrapper or .avatar or anything same classes. Now solving that will looks like nesting css selectors:
```css
.ui--mix--home--spacecraft-item-component
> .wrapper > .avatar{}

.ui--mix--home--spaceship-item-component
> .wrapper > .avatar{}

etc
```
By this way our bundle will have ton of KB lol
Or another way same to:
```css
.spacecraft-avatar{}

.spaceship-avatar{}

etc
```
This way so fast will make our code super ugly. So, my proposal is realise transpiling rcss to css which will have uniq version of selectors so our code will be clean and our bundle will be super light weight.
